name: Unlock-NetEaseMusic

on:
  schedule:
    - cron: "37 */8 * * *" # Runs every 8 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Chrome & Chromedriver
        run: |
          echo "Installing Google Chrome and Chromedriver..."
          choco install googlechrome -y
          choco install chromedriver -y --force
          echo "✅ Chrome & Chromedriver installed successfully."

      - name: Debug Chrome and Chromedriver
        shell: pwsh # 强制使用 PowerShell
        run: |
          echo "Checking Chrome version..."
          if (Test-Path "C:\Program Files\Google\Chrome\Application\chrome.exe") {
              & "C:\Program Files\Google\Chrome\Application\chrome.exe" --version
          } else {
              echo "❌ Chrome not found!"
          }

          echo "Checking Chromedriver version..."
          if (Get-Command chromedriver -ErrorAction SilentlyContinue) {
              chromedriver --version
          } else {
              echo "❌ Chromedriver not found!"
          }

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unlock script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PYTHONIOENCODING: utf-8
          PYTHONLEGACYWINDOWSSTDIO: utf-8
        run: python auto_login.py
        MUSIC_U = "00EBE8FDC34190931C2F7125036F0918B439B37F966C4D2A9474A0D4AFE64ED502D6830870B9F3AA22AB97E7CACE6B00F5031B346D7AC9783737EF366D857DDADBD0EA48A40CBAEFB93D203BF408C0A24B249FF786EF79A8280F4D06B7A98DAED65A15D2CAA72A6D390E60B86461A0E19D6F284533861CF7E6D469038195F49E587FFF593B55D3DB2839C891CFF8096FDDEB9EEB345D35C82CB055EA4D0EBB1908D2D21336F42EBCD7D1A96E8DF7678CCE12EA589A3B4058D552701206B2B77146323B84CDE9796DE339844A5B218AD48482C9E72A532D5A792113896778BA7152BFC97CBEC3A0E955A97AA982A28A8AB3108A84FC91DE9EB8860BFF92C64E254A93AE1B74DC1E049F7C1AE97582360782537333EFF23564091D95BD31D4762E265EA40C1872A3C15EA45E04348F8EF96E5DD49A0C6CCF5ECC44B5A4C481BFB739CD00892086CC5733B69E92FA4B9ED64C"
